### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by aalexpat** [gerbus/chrome-google-calendar-meeting-start-times#5]
The extension is not working anymore since the last google chrome update this week. Meeting offsets are not applied anymore

**Comment by darrenaalfonso** [comment]
Yes, not working.  Maybe due to the new Google Calendar UI updates?

**Comment by gerbus** [comment]
Thanks both. I'll take a look shortly and sort this out.

**Comment by gerbus** [comment]
#6 should fix this. I'll get this up to the chrome marketplace by EOD tomorrow.

**Comment by gerbus** [comment]
Alright this is fixed with [v1.1.1](https://github.com/gerbus/chrome-google-calendar-meeting-start-times/releases/tag/v1.1.1). 

Chrome should pull in this update in the next 4-6 hours, but if you want to update manually, you can navigate to [chrome://extensions](chrome://extensions), enable `Developer mode` (top right), and then click `Update` (top left).
